# Generated by Django 5.2 on 2025-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
