# Generated by Django 5.2.1 on 2026-02-11 09:37

from django.db import migrations


CATEGORIES = [
    {'name': 'Web Development', 'slug': 'web-development', 'description': 'Tutorials and guides on building modern web applications'},
    {'name': 'AI & Machine Learning', 'slug': 'ai-machine-learning', 'description': 'Explore the world of artificial intelligence and ML'},
    {'name': 'DevOps & Cloud', 'slug': 'devops-cloud', 'description': 'Infrastructure, deployment, and cloud computing'},
    {'name': 'Mobile Development', 'slug': 'mobile-development', 'description': 'Build beautiful native and cross-platform mobile apps'},
    {'name': 'UI/UX Design', 'slug': 'ui-ux-design', 'description': 'Design principles, tools, and best practices'},
    {'name': 'Career & Productivity', 'slug': 'career-productivity', 'description': 'Level up your developer career and workflow'},
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    for cat in CATEGORIES:
        Category.objects.get_or_create(slug=cat['slug'], defaults=cat)


def remove_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    Category.objects.filter(slug__in=[c['slug'] for c in CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_category_description_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
